version: "3"
services:

  intelephense:
    #build:
    #  context: .
    #  dockerfile: Intelephense.Dockerfile
    image: krstian/intelephense-node22-alpine
    container_name: intelephense
    environment:
      KEY: "value"
    volumes:
      - ./docker_volumes/home_kristian:/home/kristian
      - /var/www/html:/var/www/html
    #ports:
    #  - "8000:8000"
    network_mode: "host"
    #depends_on:
    #  - mssql
    #networks:
    #  - intelephense
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  intelephense-bundle-cli-client:
    # build:
    #  context: .
    #  dockerfile: Intelephense-Bundle-Cli-Client.Dockerfile
    image: krstian/intelephense-lspclientcli-python3-node22-alpine
    container_name: intelephense-client
    environment:
      KEY: "value"
    volumes:
      - ./docker_volumes/home_kristian:/home/kristian
      - /var/www/html:/var/www/html
    #ports:
    #  - "8000:8000"
    network_mode: "host"
    #depends_on:
    #  - mssql
    #networks:
    #  - intelephense
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  intelephense-bundle-cli-client-jqgit:
    build:
     context: .
     dockerfile: Intelephense-Bundle-Cli-Client-jqgit.Dockerfile
    # image: krstian/intelephense-lspclientcli-python3-node22-alpine
    container_name: intelephense-client-jqgit
    environment:
      KEY: "value"
    volumes:
      - ./docker_volumes/home_kristian:/home/kristian
      - /var/www/html:/var/www/html
    #ports:
    #  - "8000:8000"
    network_mode: "host"
    #depends_on:
    #  - mssql
    #networks:
    #  - intelephense
    logging:
      options:
        max-size: "10m"
        max-file: "3"



#networks:
#  intelephense:
#    driver: bridge
